export interface IMiembroView {
	foto: string;
	codMiembro: number;
	nombreCompleto: string;
	primerNombre: string;
	segundoNombre: string;
	primerApellido: string;
	segundoApellido: string;
	fechaNacimiento: string;
	cedula: string;
	nombreApellidoCompleto: string;
	sexo: string;
	codInstitucion: number;
	siglasInstitucion: string;
	institucion: string;
	codNacionalidad: number;
	nacionalidad: string;
	codProfesion: number;
	profesion: string;
	profesionReal: string;
	codNivelAcademico: number;
	nivelAcademico: string;
	codNivelProfesion: number;
	nivelProfesion: string;
	codRamaProfesion: number;
	ramaProfesion: string;
	codEspecialidad: number;
	especialidad: string;
	codSubEspecialidad: number;
	subEspecialidad: string;
	codEstadoCivil: number;
	estadoCivil: string;
	codRango: number;
	rango: string;
	rangoAbreviado: string;
	nivelRango: string;
	codDepartamento: number;
	departamento: string;
	categoriaDepartamento: string;
	categoriaOrganicaDepartamento: string;
	codCargo: number;
	estado: string;
	codCompania: number;
	compania: string;
	codBatallon: number;
	batallon: string;
	codBrigada: number;
	brigada: string;
	codTipoIngreso: number;
	tipoIngreso: string;
	codTipLicConducir: number | null;
	licenciaConducir: string;
	codLugarNacimiento: number;
	lugarNacimiento: string;
	fechaRegistro: string;
	oficioQueManeja: string;
	edadIngreso: number;
	ocupacionAntesIngreso: string;
	motivoIngreso: string;
	estatura: string;
	pesos: number;
	codColorPiel: number;
	colorPiel: string;
	codColorOjos: number;
	colorOjos: string;
	codTipoPelo: number;
	tipoPiel: string;
	codTipoSangre: number;
	tipoSangre: string;
	marcasSicatrices: string;
	codEstadoMiembro: number;
	estadoMiembro: string;
	categoriaEstatus: string;
	esReingreso: boolean | null;
	fechaCreacion: string;
	fechaModificacion: string | null;
	codUsuario: number | null;
	status: boolean;
	fechaUltimoAscenso: string | null;
	fueDepuradoMedicamente: boolean;
	fueDepurado: boolean;
	cargo: string;
	descripcionCargo: string;
	vaParaDepuracion: boolean;
	fueDepuradoPsicologicamente: boolean;
	codAnterior: string;
	expr1: number;
	codCategoriaDepartamento: number;
	codNivelRango: number;
	documento: string;
	codTipoDocumento: number | null;
	tipoDocumento: string;
	descripcionRango: string;
	noCarnet: string;
	articuloPorGenero: string;
	sueldoRango: number | null;
	sueldoPorRiesgo: number | null;
	codCategoriaEstatus: number;
	noOrdenRango: number;
	codNivel: number | null;
	comando: boolean;
	graduadoAcademia: boolean | null;
	codPromocionAcademia: number | null;
	noEscalafonGeneral: number | null;
	noEscalafonPorNivelProfesional: number | null;
	noEscalafonPorProfesion: number | null;
	noEscalafonPorProfesionRango: number | null;
	esMilitar: boolean;
	anosEnRangoActual1: string;
	anosEnLaInstitucion1: string;
	edad1: string;
	anosEnRangoActual: number | null;
	anosEnLaInstitucion: number | null;
	edad: number | null;
	sueldo: number;
	sueldoCargo: number;
	sueldoRiesgo: number;
	compensacionEspecial: number;
	prima: number;
	slogan: string;
	codRangoSiguiente: number | null;
	noOrdenProfesion: number;
	tipoPelo: string;
	r: string;
	rangoIngreso: string;
	fechaDeIngreso: string | null;
	fechaUltimoMovimiento: string | null;
	anosEnLaFuncionActual: string;
	notificacion: string;
	escalafon: number | null;
	fechaCalculadaTiempoServicio: string | null;
	fechaCalculadaTiempoRango: string | null;
	fechaCalculadaTiempoInstitucion: string | null;
	fechaReingreso: string | null;
	codOrden: number | null;
	organoEjecutor: string;
	codOrganoEjecutor: number | null;
}
