export const AppPermissions = {
	ADMINISTRADOR: 'ADMINISTRADOR GENERAL',
	CONSULTA: 'CONSULTA GENERAL',
	MANTENIMIENTO: 'MODULO MANTENIMIENTO',
	ESTADISTICAS: 'MODULO ESTADISTICAS',
	ACCESOS: 'MODULO USUARIOS',
	REPORTERIA: 'MODULO REPORTERIA',
	PROVEEDORES: 'MODULO PROVEEDORES',
};
