export const AppPermissions = {
	ADMINISTRADOR: 'ADMINISTRADOR GENERAL',
	EXISTENCIA: 'MODULO EXISTENCIAS',

	TRANSACCIONES: 'MODULO TRANSACCIONES',
	TRANSACCIONES_CREAR_CARGO_DESCARGO: 'TRANSACCIONES CREAR CARGO DESCARGO',
	TRANSACCIONES_VISUALIZAR_DETALLES: 'TRANSACCIONES VISUALIZAR DETALLES',
	TRANSACCIONES_VISUALIZAR_DOCUMENTOS: 'TRANSACCIONES VISUALIZAR DOCUMENTOS',
	TRANSACCIONES_GENERAR_FORMULARIO_53: 'TRANSACCIONES GENERAR FORMULARIO 53',
	TRANSACCIONES_ADJUNTAR_FORMULARIO_53:
		'TRANSACCIONES ADJUNTAR FORMULARIO 53',
	TRANSACCIONES_CARGAR_INVENTARIO_EXCEL:
		'TRANSACCIONES CARGAR INVENTARIO EXCEL',

	EMPRESAS: 'MODULO EMPRESAS',
	EMPRESAS_CREAR: 'EMPRESAS CREAR',
	EMPRESAS_EDITAR: 'EMPRESAS EDITAR',
	EMPRESAS_ELIMINAR: 'EMPRESAS ELIMINAR',

	EMPRESAS_VISUALIZAR_ORDENES: 'EMPRESAS VISUALIZAR ORDENES',
	EMPRESAS_CREAR_ORDEN: 'EMPRESAS CREAR ORDEN',
	EMPRESAS_EDITAR_ORDEN: 'EMPRESAS EDITAR ORDEN',
	EMPRESAS_ELIMINAR_ORDEN: 'EMPRESAS ELIMINAR ORDEN',
	EMPRESAS_VISUALIZAR_DETALLES_ORDEN: 'EMPRESAS VISUALIZAR DETALLES ORDEN',
	EMPRESAS_VISUALIZAR_DOCUMENTOS_ORDEN:
		'EMPRESAS VISUALIZAR DOCUMENTOS ORDEN',

	USUARIOS: 'MODULO USUARIOS',
};
